apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanzu-java-web-app
  namespace: test-ns
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  selector:
    matchLabels:
      containerapp.apps.tanzu.vmware.com/app-name: tanzu-java-web-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        containerapp.apps.tanzu.vmware.com/app-name: tanzu-java-web-app
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: key1
              value: test
            - name: JAVA_TOOL_OPTIONS
              value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.health.probes.enabled=true -Dserver.port=8080 -Dserver.shutdown.grace-period=24s
          image: tanzuplaycaapub.azurecr.io/tap-saas/tanzu-java-web-app@sha256:3de73475c263392b3b3e0067a90e4d945e5b2573ac5feb537da035cea2c3aa23
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: workload
          ports:
            - containerPort: 8080
              name: main
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          startupProbe:
            failureThreshold: 120
            httpGet:
              path: /readyz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: tanzu-tmp
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      # serviceAccount: tanzu-java-web-app
      # serviceAccountName: tanzu-java-web-app
      terminationGracePeriodSeconds: 300
      # topologySpreadConstraints:
      #   - labelSelector:
      #       matchLabels:
      #         containerapp.apps.tanzu.vmware.com/app-name: tanzu-java-web-app
      #     matchLabelKeys:
      #       - pod-template-hash
      #     maxSkew: 1
      #     topologyKey: topology.kubernetes.io/zone
      #     whenUnsatisfiable: ScheduleAnyway
      #   - labelSelector:
      #       matchLabels:
      #         containerapp.apps.tanzu.vmware.com/app-name: tanzu-java-web-app
      #     matchLabelKeys:
      #       - pod-template-hash
      #     maxSkew: 1
      #     topologyKey: topology.kubernetes.io/hostname
      #     whenUnsatisfiable: ScheduleAnyway
      volumes:
        - emptyDir: {}
          name: tanzu-tmp

