apiVersion: v1
kind: Service
metadata:
  name: tanzu-java-web-app
  namespace: test-ns
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    containerapp.apps.tanzu.vmware.com/app-name: tanzu-java-web-app
  type: ClusterIP
